[package]
name = "loopback-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
device_kit = { path = ".." }

[build-dependencies]
napi-build = "2"
