/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function registerSource(channel: number, capacityFrames?: number | undefined | null): boolean
export declare function pushAudioFrame(channel: number, pcm: Float32Array, timestamp?: number | undefined | null): boolean
export declare function setSourceGain(channel: number, gain: number): boolean
export declare function setSourceMute(channel: number, mute: boolean): boolean
export declare function monotonicTimeNs(): number
